### ISSUE TITLE
useFormFields is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by jianly** [imgarylai/use-mailchimp-form#50]

**Comment by imgarylai** [comment]
`useFormFields` is a hook function. The return values are a React state and a helper function. 

The [usage](https://github.com/imgarylai/use-mailchimp-form#usage) section shows an example of how to use it. 

However, it is not recommended to use my `useFormFields` in your project. It is implemented to show the usage of this package. 

I would recommend you use other React form library to implement your own form, e.g., [react-hook-form](https://react-hook-form.com/), [formik](https://formik.org/), or [react-final-form](https://final-form.org/react).

I would close this issue first. 

Thank you.
